In [12]:
import os
import sys

import pandas as pd
import numpy as np
from datetime import datetime as dt
import calendar
import matplotlib.pyplot as plt

### To do
average also for annual with only months T>0C

In [13]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
import warnings
warnings.filterwarnings('ignore')

In [15]:
data_dir = '/Users/maoyabassiouni/Documents/DATA/Projects/OLNI'

# Combine annual files

In [16]:
models = ['ACCESS-CM2',
          'CanESM5',
          'CESM2',
          'CNRM-CM6-1',
          'EC-Earth3-Veg-LR',
          'FGOALS-g3',
          'GFDL-CM4',
          'GISS-E2-1-G',
          'IITM-ESM',
          'INM-CM5-0',
          'IPSL-CM6A-LR',
          'KIOST-ESM',
          'MIROC6',
          'MPI-ESM1-2-LR',
          'MRI-ESM2-0',
          'NorESM2-MM',
          'UKESM1-0-LL']

In [25]:
scenarios = [ 'historical', 'ssp245',  'ssp585']

variables_A = ['tas', 'hurs', 'pr', 'rsds']

In [19]:
source_id = models[0]
scenario = scenarios[0]
ff = os.path.join(data_dir, 'grid_data_extract', 'CMIP', '%s_%s_%s.csv' % (variables_A[0], scenario, source_id))
df = pd.read_csv(ff)
df['timestamp'] = [dt.strptime(dti, '%Y-%m-%d %H:%M:%S')
                                 for dti in df['datetime'].values]
df['month'] = [dti.astype('datetime64[M]').astype(int) % 12 + 1 for dti in df['timestamp'].values]
df['year'] = pd.DatetimeIndex(df['timestamp']).year
df = df.drop(['datetime', 'Unnamed: 0', '%s_%s_%s' % (variables_A[0], scenario, source_id) ], axis=1)

for source_id in models:
    for variable in variables_A:
        ff = os.path.join(data_dir, 'grid_data_extract', 'CMIP', '%s_%s_%s.csv' % (variable, scenario, source_id))
        dfi = pd.read_csv(ff)
        df['%s_%s_%s' % (variable, scenario, source_id)] = dfi['%s_%s_%s' % (variable, scenario, source_id)]
        if variable == 'tas':
            df['%s_%s_%s' % (variable, scenario, source_id)] = df['%s_%s_%s' % (variable, scenario, source_id)] - 273.15
        if variable == 'pr':
            df['%s_%s_%s' % (variable, scenario, source_id)] \
            = df['%s_%s_%s' % (variable, scenario, source_id)] * 60 * 60 * 24 / 1000 # [kg m-2 s-1] -> m


#df.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_%s_%s.csv' % (scenario, source_id)))
df.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_%s_models.csv' % (scenario)))
print(df.keys(), len(df.index))

Index(['Lat', 'Lon', 'sp', 'timestamp', 'month', 'year',
       'tas_historical_ACCESS-CM2', 'hurs_historical_ACCESS-CM2',
       'pr_historical_ACCESS-CM2', 'rsds_historical_ACCESS-CM2',
       'tas_historical_CanESM5', 'hurs_historical_CanESM5',
       'pr_historical_CanESM5', 'rsds_historical_CanESM5',
       'tas_historical_CESM2', 'hurs_historical_CESM2', 'pr_historical_CESM2',
       'rsds_historical_CESM2', 'tas_historical_CNRM-CM6-1',
       'hurs_historical_CNRM-CM6-1', 'pr_historical_CNRM-CM6-1',
       'rsds_historical_CNRM-CM6-1', 'tas_historical_EC-Earth3-Veg-LR',
       'hurs_historical_EC-Earth3-Veg-LR', 'pr_historical_EC-Earth3-Veg-LR',
       'rsds_historical_EC-Earth3-Veg-LR', 'tas_historical_FGOALS-g3',
       'hurs_historical_FGOALS-g3', 'pr_historical_FGOALS-g3',
       'rsds_historical_FGOALS-g3', 'tas_historical_GFDL-CM4',
       'hurs_historical_GFDL-CM4', 'pr_historical_GFDL-CM4',
       'rsds_historical_GFDL-CM4', 'tas_historical_GISS-E2-1-G',
       'hurs_historical_GISS-E2-1-G', 'pr_historical_GISS-E2-1-G',
       'rsds_historical_GISS-E2-1-G', 'tas_historical_IITM-ESM',
       'hurs_historical_IITM-ESM', 'pr_historical_IITM-ESM',
       'rsds_historical_IITM-ESM', 'tas_historical_INM-CM5-0',
       'hurs_historical_INM-CM5-0', 'pr_historical_INM-CM5-0',
       'rsds_historical_INM-CM5-0', 'tas_historical_IPSL-CM6A-LR',
       'hurs_historical_IPSL-CM6A-LR', 'pr_historical_IPSL-CM6A-LR',
       'rsds_historical_IPSL-CM6A-LR', 'tas_historical_KIOST-ESM',
       'hurs_historical_KIOST-ESM', 'pr_historical_KIOST-ESM',
       'rsds_historical_KIOST-ESM', 'tas_historical_MIROC6',
       'hurs_historical_MIROC6', 'pr_historical_MIROC6',
       'rsds_historical_MIROC6', 'tas_historical_MPI-ESM1-2-LR',
       'hurs_historical_MPI-ESM1-2-LR', 'pr_historical_MPI-ESM1-2-LR',
       'rsds_historical_MPI-ESM1-2-LR', 'tas_historical_MRI-ESM2-0',
       'hurs_historical_MRI-ESM2-0', 'pr_historical_MRI-ESM2-0',
       'rsds_historical_MRI-ESM2-0', 'tas_historical_NorESM2-MM',
       'hurs_historical_NorESM2-MM', 'pr_historical_NorESM2-MM',
       'rsds_historical_NorESM2-MM', 'tas_historical_UKESM1-0-LL',
       'hurs_historical_UKESM1-0-LL', 'pr_historical_UKESM1-0-LL',
       'rsds_historical_UKESM1-0-LL'],
      dtype='object') 809820

In [20]:
df

,Lat,Lon,sp,timestamp,month,year,tas_historical_ACCESS-CM2,hurs_historical_ACCESS-CM2,pr_historical_ACCESS-CM2,rsds_historical_ACCESS-CM2,...,pr_historical_MRI-ESM2-0,rsds_historical_MRI-ESM2-0,tas_historical_NorESM2-MM,hurs_historical_NorESM2-MM,pr_historical_NorESM2-MM,rsds_historical_NorESM2-MM,tas_historical_UKESM1-0-LL,hurs_historical_UKESM1-0-LL,pr_historical_UKESM1-0-LL,rsds_historical_UKESM1-0-LL
0,36.3706,-5.5783,54.0,1850-01-15 12:00:00,1,1850,14.736475,61.445312,0.002035,110.822197,...,0.002683,101.042427,14.127710,65.535385,0.001785,110.281837,9.916895,71.695312,0.003383,108.923973
1,36.3706,-5.5783,54.0,1850-02-14 00:00:00,2,1850,14.532373,59.914062,0.000796,137.606644,...,0.000781,161.006409,14.279047,66.314178,0.001816,167.901199,10.593164,71.359375,0.001342,140.404709
2,36.3706,-5.5783,54.0,1850-03-15 12:00:00,3,1850,15.175439,63.781250,0.002174,180.951706,...,0.001330,215.504120,13.542657,63.922840,0.002337,199.853119,12.494531,77.375000,0.001722,211.590591
3,36.3706,-5.5783,54.0,1850-04-15 00:00:00,4,1850,16.890527,73.085938,0.000436,258.005035,...,0.002001,256.385040,17.416315,68.710907,0.000899,274.026031,14.359033,69.500000,0.000450,244.250122
4,36.3706,-5.5783,54.0,1850-05-15 12:00:00,5,1850,17.174707,77.132812,0.002778,304.144989,...,0.000368,289.610443,18.255823,66.887589,0.000087,325.821136,17.154688,69.257812,0.000740,314.592896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
809815,69.7389,26.9581,134.0,2014-08-15 12:00:00,8,2014,6.754541,85.023438,0.002751,136.922043,...,0.002330,120.582649,10.609460,79.426216,0.003078,133.687271,9.614160,81.851562,0.000642,101.374802
809816,69.7389,26.9581,134.0,2014-09-15 00:00:00,9,2014,1.713037,91.039062,0.002087,57.327900,...,0.003993,66.264595,9.259790,79.796188,0.000657,91.214211,5.830225,87.148438,0.001677,70.316818
809817,69.7389,26.9581,134.0,2014-10-15 12:00:00,10,2014,-1.817480,96.539062,0.002457,24.852823,...,0.001023,23.968290,-0.858099,88.705551,0.001430,20.762609,2.079980,87.656250,0.001006,20.373333
809818,69.7389,26.9581,134.0,2014-11-15 00:00:00,11,2014,-11.040137,108.210938,0.001327,2.470950,...,0.000776,1.888633,-6.459296,88.180580,0.001731,1.718729,-11.173682,101.289062,0.001683,2.270879
809819,69.7389,26.9581,134.0,2014-12-15 12:00:00,12,2014,-11.552344,114.570312,0.001155,0.000000,...,0.001126,0.000000,-5.313025,90.837624,0.001549,0.000000,-12.731055,99.585938,0.001834,0.000000

In [26]:
scenario = scenarios[1]
ff = os.path.join(data_dir, 'grid_data_extract', 'CMIP', '%s_%s_%s.csv' % (variables_A[0], scenario, source_id))
df = pd.read_csv(ff)
#print(df.keys())
df['timestamp'] = [dt.strptime(dti, '%Y-%m-%d %H:%M:%S')
                                 for dti in df['time'].values]
df['month'] = [dti.astype('datetime64[M]').astype(int) % 12 + 1 for dti in df['timestamp'].values]
df['year'] = pd.DatetimeIndex(df['timestamp']).year
df = df.drop(['time', 'Unnamed: 0', '%s_%s_%s' % (variables_A[0], scenario, source_id) ], axis=1)

for source_id in models:
    for scenario in scenarios[1:]:
        for variable in variables_A:
            ff = os.path.join(data_dir, 'grid_data_extract', 'CMIP', '%s_%s_%s.csv' % (variable, scenario, source_id))
            dfi = pd.read_csv(ff)
            df['%s_%s_%s' % (variable, scenario, source_id)] = dfi['%s_%s_%s' % (variable, scenario, source_id)]
            if variable == 'tas':
                df['%s_%s_%s' % (variable, scenario, source_id)] = df['%s_%s_%s' % (variable, scenario, source_id)] - 273.15
            if variable == 'pr':
                df['%s_%s_%s' % (variable, scenario, source_id)] \
                = df['%s_%s_%s' % (variable, scenario, source_id)] * 60 * 60 * 24 / 1000 # [kg m-2 s-1] -> m
#df.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_proj_%s.csv' % (source_id))) 
df.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_proj_models.csv')) 

print(df.keys(), len(df.index))

Index(['Lat', 'Lon', 'sp', 'timestamp', 'month', 'year',
       'tas_ssp245_ACCESS-CM2', 'hurs_ssp245_ACCESS-CM2',
       'pr_ssp245_ACCESS-CM2', 'rsds_ssp245_ACCESS-CM2',
       ...
       'pr_ssp585_NorESM2-MM', 'rsds_ssp585_NorESM2-MM',
       'tas_ssp245_UKESM1-0-LL', 'hurs_ssp245_UKESM1-0-LL',
       'pr_ssp245_UKESM1-0-LL', 'rsds_ssp245_UKESM1-0-LL',
       'tas_ssp585_UKESM1-0-LL', 'hurs_ssp585_UKESM1-0-LL',
       'pr_ssp585_UKESM1-0-LL', 'rsds_ssp585_UKESM1-0-LL'],
      dtype='object', length=142) 422088

In [27]:
df.head(5)

,Lat,Lon,sp,timestamp,month,year,tas_ssp245_ACCESS-CM2,hurs_ssp245_ACCESS-CM2,pr_ssp245_ACCESS-CM2,rsds_ssp245_ACCESS-CM2,...,pr_ssp585_NorESM2-MM,rsds_ssp585_NorESM2-MM,tas_ssp245_UKESM1-0-LL,hurs_ssp245_UKESM1-0-LL,pr_ssp245_UKESM1-0-LL,rsds_ssp245_UKESM1-0-LL,tas_ssp585_UKESM1-0-LL,hurs_ssp585_UKESM1-0-LL,pr_ssp585_UKESM1-0-LL,rsds_ssp585_UKESM1-0-LL
0,36.3706,-5.5783,54.0,2015-01-16 12:00:00,1,2015,12.900781,60.859375,0.006550,104.332291,...,0.000642,119.231888,12.992578,74.203125,0.001332,118.123260,13.562646,61.218750,0.001412,95.375717
1,36.3706,-5.5783,54.0,2015-02-15 00:00:00,2,2015,13.154199,61.500000,0.001501,158.037384,...,0.001611,138.980438,13.282861,75.835938,0.000605,144.466537,12.527979,66.117188,0.002647,155.648865
2,36.3706,-5.5783,54.0,2015-03-16 12:00:00,3,2015,14.839258,67.929688,0.002703,220.098450,...,0.001686,211.004547,13.092432,75.390625,0.001426,188.377106,14.131006,77.859375,0.002231,205.619492
3,36.3706,-5.5783,54.0,2015-04-16 00:00:00,4,2015,15.916162,73.515625,0.001039,282.734253,...,0.000125,294.631622,15.516748,60.992188,0.001114,243.143066,17.290186,72.179688,0.001230,274.431274
4,36.3706,-5.5783,54.0,2015-05-16 12:00:00,5,2015,18.161768,78.921875,0.000608,314.070312,...,0.000118,338.491272,18.674463,68.695312,0.000373,307.419189,18.484033,78.187500,0.002546,266.634399

# Process growing season annual timeseries

In [28]:
gs_df = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'growing_season_locs_b.csv'))

In [29]:
gs_df

,Unnamed: 0,Lat,Lon,sp_id,months_gs,gs_lai,peak_gs_month,peak_lai
0,0,34.929444,32.931111,121.0,"[4, 5, 6, 7, 8, 9]",1.279743,6,1.413393
1,1,34.929444,32.931111,129.0,"[4, 5, 6, 7, 8, 9]",1.279743,6,1.413393
2,2,34.952222,32.830556,129.0,"[4, 5, 6, 7, 8, 9]",1.528348,6,1.712532
3,3,35.013889,33.050000,121.0,"[3, 4, 5, 6, 7, 8]",0.903121,4,0.968772
4,4,35.020000,32.627500,121.0,"[4, 5, 6, 7, 8, 9]",1.404534,6,1.522782
...,...,...,...,...,...,...,...,...
989,989,67.999444,24.236111,118.0,"[6, 7, 8, 9]",1.146759,7,1.423312
990,990,68.995278,19.427500,118.0,"[6, 7, 8]",2.025214,7,2.366606
991,991,69.454167,30.036111,134.0,"[6, 7, 8, 9]",1.448153,7,1.832165
992,992,69.583056,28.898056,134.0,"[6, 7, 8, 9]",0.697611,7,0.841111
993,993,69.738889,26.958056,134.0,"[6, 7, 8, 9]",1.277617,7,1.603358

In [30]:
#data_combined = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_proj_%s.csv' % (source_id)))
data_combined = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_proj_models.csv'))

data_combines = data_combined.drop(['Unnamed: 0',], axis=1)

keys = [k for k in data_combined.keys() if k not in ['Lon', 'Lat', 'sp', 'year', 'month', 'timestamp']]

data_ym = data_combined.groupby(['Lon', 'Lat', 'sp', 'year']).mean()
data_ym = data_ym.drop(['month',], axis=1)
v_gs = []
v_gs_p = []
for lon, lat, sp, year in data_ym.index:
    
    gsi = gs_df[(np.round(gs_df['Lon'], 4) == np.round(lon, 4)) & (np.round(gs_df['Lat'], 4) == np.round(lat, 4))]
    if len(gsi.index)>=1:
        months_gs = gsi['months_gs'].values[0]
        months_gs = [np.int(m) for m in months_gs[1:-1].split(',')]
        peak_gs_month = gsi['peak_gs_month'].values[0]
        data_gs = data_combined[(data_combined['Lon']==lon) 
                       & (data_combined['Lat']==lat) 
                       & (data_combined['year']==year)]
        for m in range(1, 13):
            if m not in months_gs:
                data_gs = data_gs[data_gs['month']!=m]
        
        v_gs.append([np.mean(data_gs[kk]) for kk in keys])
        data_gs_peak = data_gs[data_gs['month']==peak_gs_month]
        v_gs_p.append([np.mean(data_gs_peak[kk]) for kk in keys])
    else:
        print(len(gsi.index)==0, lon, lat, year)
        v_gs.append([np.nan for kk in keys])
        v_gs_p.append([np.nan for kk in keys])

for v, kk in zip(zip(*v_gs), keys):
    data_ym['%s_gs' %kk] = v
for v, kk in zip(zip(*v_gs_p), keys):
    data_ym['%s_gs_peak' %kk] = v
data_ym = data_ym.reset_index()
data_ym.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_proj_models_annual.csv'))
#data_ym.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_proj_%s_annual.csv' % (source_id)))

In [31]:
data_combined = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_historical_models.csv'))

#data_combined = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'CMIP_historical_%s.csv' % (source_id)))
data_combines = data_combined.drop(['Unnamed: 0',], axis=1)

keys = [k for k in data_combined.keys() if k not in ['Lon', 'Lat', 'sp', 'year', 'month', 'timestamp']]

data_ym = data_combined.groupby(['Lon', 'Lat', 'sp', 'year']).mean()
data_ym = data_ym.drop(['month',], axis=1)
v_gs = []
v_gs_p = []
for lon, lat, sp, year in data_ym.index:
    
    gsi = gs_df[(np.round(gs_df['Lon'], 4) == np.round(lon, 4)) & (np.round(gs_df['Lat'], 4) == np.round(lat, 4))]
    if len(gsi.index)>=1:
        months_gs = gsi['months_gs'].values[0]
        months_gs = [np.int(m) for m in months_gs[1:-1].split(',')]
        peak_gs_month = gsi['peak_gs_month'].values[0]
        data_gs = data_combined[(data_combined['Lon']==lon) 
                       & (data_combined['Lat']==lat) 
                       & (data_combined['year']==year)]
        for m in range(1, 13):
            if m not in months_gs:
                data_gs = data_gs[data_gs['month']!=m]
        
        v_gs.append([np.mean(data_gs[kk]) for kk in keys])
        data_gs_peak = data_gs[data_gs['month']==peak_gs_month]
        v_gs_p.append([np.mean(data_gs_peak[kk]) for kk in keys])
    else:
        print(len(gsi.index)==0, lon, lat, year)
        v_gs.append([np.nan for kk in keys])
        v_gs_p.append([np.nan for kk in keys])

for v, kk in zip(zip(*v_gs), keys):
    data_ym['%s_gs' %kk] = v
for v, kk in zip(zip(*v_gs_p), keys):
    data_ym['%s_gs_peak' %kk] = v
data_ym = data_ym.reset_index()
#data_ym.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_historical_%s_annual.csv' % (source_id)))
data_ym.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_historical_models_annual.csv'))

In [32]:
data_ym

,Lon,Lat,sp,year,Unnamed: 0,tas_historical_ACCESS-CM2,hurs_historical_ACCESS-CM2,pr_historical_ACCESS-CM2,rsds_historical_ACCESS-CM2,tas_historical_CanESM5,...,pr_historical_MRI-ESM2-0_gs_peak,rsds_historical_MRI-ESM2-0_gs_peak,tas_historical_NorESM2-MM_gs_peak,hurs_historical_NorESM2-MM_gs_peak,pr_historical_NorESM2-MM_gs_peak,rsds_historical_NorESM2-MM_gs_peak,tas_historical_UKESM1-0-LL_gs_peak,hurs_historical_UKESM1-0-LL_gs_peak,pr_historical_UKESM1-0-LL_gs_peak,rsds_historical_UKESM1-0-LL_gs_peak
0,-8.8250,43.2562,129.0,1850,126725.5,10.474369,83.675130,0.003450,155.497793,11.342254,...,0.004549,226.881485,14.874597,78.959450,0.002270,204.188904,20.880762,65.093750,0.000519,301.865448
1,-8.8250,43.2562,129.0,1851,126737.5,10.463180,80.464844,0.002578,169.324965,12.645586,...,0.005509,259.163269,17.491174,71.886734,0.000523,277.319885,18.409326,69.953125,0.002147,331.836761
2,-8.8250,43.2562,129.0,1852,126749.5,10.237492,80.360026,0.002747,169.811425,11.280669,...,0.003222,268.484589,19.593469,70.337982,0.000984,282.938751,16.541162,79.007812,0.000649,312.818268
3,-8.8250,43.2562,129.0,1853,126761.5,10.085657,81.562500,0.002332,157.974248,12.463007,...,0.004946,277.773895,17.745721,70.024948,0.001641,264.003876,19.071924,73.273438,0.002517,295.908447
4,-8.8250,43.2562,129.0,1854,126773.5,9.930872,83.350911,0.003027,159.984982,11.637837,...,0.003942,266.112030,18.858606,68.526199,0.001250,282.680511,21.309473,55.531250,0.001535,325.396454
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67480,29.5011,66.3025,118.0,2010,797885.5,-0.378210,88.572266,0.001844,86.931651,3.063013,...,0.002318,231.428268,12.810236,70.095200,0.002881,190.507401,11.490381,75.992188,0.004396,188.321335
67481,29.5011,66.3025,118.0,2011,797897.5,-2.949886,86.916016,0.002188,87.094636,0.818351,...,0.004940,184.629974,14.640161,79.252319,0.004796,164.771667,9.801172,77.804688,0.003502,219.613022
67482,29.5011,66.3025,118.0,2012,797909.5,-2.666337,89.540365,0.002003,85.985540,1.733329,...,0.002450,184.529419,13.104395,73.272690,0.003145,185.202576,12.415918,76.992188,0.004744,194.916840
67483,29.5011,66.3025,118.0,2013,797921.5,-1.166785,88.067708,0.002234,91.605202,1.785410,...,0.004168,231.090607,12.196771,71.431412,0.003029,174.271835,15.047998,72.828125,0.003288,145.489838
67484,29.5011,66.3025,118.0,2014,797933.5,-1.909521,88.898438,0.002320,91.023858,2.477174,...,0.001088,186.936752,11.769006,70.006493,0.003122,158.472229,13.250635,76.742188,0.006533,219.890274

In [16]:
data_co2 = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'co2s_ssp245_GFDL-ESM4.csv'))
data_co2['timestamp'] = [dt.strptime(dti, '%Y-%m-%d %H:%M:%S')
                                 for dti in data_co2['datetime'].values]
data_co2['year'] = pd.DatetimeIndex(data_co2['timestamp']).year
data_co2 = data_co2.drop(['datetime', 'Unnamed: 0', 'CO2_ssp245', 'timestamp'], axis=1)

for scenario in scenarios[1:]:
    data_co2i = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'co2s_%s_GFDL-ESM4.csv' %scenario))
    data_co2['CO2_%s' % scenario] = data_co2i['CO2_%s' % scenario] * 10 ** (-6)
    
data_co2.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_proj_co2.csv'))
data_co2

    year  CO2_ssp245  CO2_ssp370  CO2_ssp585
0   2015    0.000310    0.000310    0.000310
1   2016    0.000312    0.000312    0.000312
2   2017    0.000314    0.000314    0.000314
3   2018    0.000316    0.000317    0.000316
4   2019    0.000319    0.000318    0.000318
..   ...         ...         ...         ...
81  2096    0.000470    0.000641    0.000824
82  2097    0.000470    0.000647    0.000834
83  2098    0.000471    0.000653    0.000845
84  2099    0.000472    0.000659    0.000855
85  2100    0.000472    0.000666    0.000866

[86 rows x 4 columns]

In [17]:
scenario = 'historical'
data_co2 = pd.read_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP', 'co2s_historical_GFDL-ESM4.csv'))
data_co2['timestamp'] = [dt.strptime(dti, '%Y-%m-%d %H:%M:%S')
                                 for dti in data_co2['datetime'].values]
data_co2['year'] = pd.DatetimeIndex(data_co2['timestamp']).year
data_co2 = data_co2.drop(['datetime', 'Unnamed: 0',  'timestamp'], axis=1)
data_co2['CO2_%s' % scenario] = data_co2['CO2_%s' % scenario] * 10 ** (-6)

data_co2.to_csv(os.path.join(data_dir, 'grid_data_extract', 'CMIP_historical_co2.csv'))
data_co2

     CO2_historical  year
0          0.000225  1850
1          0.000225  1851
2          0.000225  1852
3          0.000225  1853
4          0.000225  1854
..              ...   ...
160        0.000303  2010
161        0.000303  2011
162        0.000305  2012
163        0.000307  2013
164        0.000309  2014

[165 rows x 2 columns]